import { Prisma } from '@prisma/client';
import { describe, expect, it } from 'vitest';

const expectedModels = {
  DockingJob: [
    'id',
    'receptorId',
    'ligandId',
    'engine',
    'engineVersion',
    'status',
    'parametersJson',
    'score',
    'poseArtifactPath',
    'errorMessage',
    'createdAt',
    'startedAt',
    'completedAt',
  ],
  Approval: ['id', 'runId', 'type', 'status', 'snapshotHash', 'selectionJson', 'note', 'createdAt'],
  Artifact: [
    'id',
    'runId',
    'type',
    'format',
    'relativePath',
    'mimeType',
    'byteSize',
    'sha256',
    'templateVersion',
    'createdAt',
  ],
  CacheEntry: [
    'id',
    'cacheKey',
    'connectorId',
    'connectorVersion',
    'method',
    'methodVersion',
    'inputHash',
    'outputHash',
    'schemaVersion',
    'valueJson',
    'createdAt',
    'expiresAt',
    'lastAccessedAt',
  ],
  Candidate: [
    'id',
    'runId',
    'candidateKey',
    'candidateType',
    'peptide',
    'start',
    'end',
    'length',
    'allele',
    'createdAt',
  ],
  ConstraintOutcome: [
    'id',
    'runId',
    'candidateId',
    'snapshotHash',
    'ruleId',
    'ruleVersion',
    'severity',
    'outcome',
    'message',
    'evidenceRefsJson',
    'relatedCandidateId',
    'createdAt',
  ],
  EvidenceSummary: [
    'id',
    'runId',
    'candidateId',
    'snapshotHash',
    'bindingQuality',
    'weightedMean',
    'variance',
    'agreement',
    'completeness',
    'consensus',
    'detailsJson',
    'createdAt',
  ],
  GraphEdge: [
    'id',
    'runId',
    'edgeType',
    'sourceNodeId',
    'targetNodeId',
    'propertiesJson',
    'createdAt',
  ],
  GraphNode: ['id', 'runId', 'nodeType', 'entityId', 'label', 'propertiesJson', 'createdAt'],
  NormalizedObservation: [
    'id',
    'runId',
    'candidateId',
    'predictionObservationId',
    'field',
    'rawValue',
    'normalizedValue',
    'profileVersion',
    'transformationJson',
    'createdAt',
  ],
  PopulationCoverageResult: [
    'id',
    'runId',
    'populationId',
    'classMode',
    'purpose',
    'candidateIdsJson',
    'projectedCoverage',
    'averageHits',
    'pc90',
    'provenanceJson',
    'snapshotHash',
    'createdAt',
  ],
  PredictionObservation: [
    'id',
    'runId',
    'candidateId',
    'predictorExecutionId',
    'rawScoresJson',
    'unitsJson',
    'inputHash',
    'outputHash',
    'observedAt',
    'createdAt',
    'supersedesId',
  ],
  PredictorExecution: [
    'id',
    'runId',
    'stageId',
    'connectorId',
    'connectorVersion',
    'method',
    'methodVersion',
    'status',
    'sourceStatus',
    'parametersJson',
    'inputHash',
    'outputHash',
    'cacheKey',
    'fixtureId',
    'attemptCount',
    'errorCode',
    'startedAt',
    'completedAt',
  ],
  Project: ['id', 'name', 'organism', 'proteinName', 'description', 'createdAt', 'updatedAt'],
  ProteinInput: [
    'id',
    'projectId',
    'originalFasta',
    'header',
    'normalizedSequence',
    'sequenceLength',
    'sha256',
    'validationProfileVersion',
    'createdAt',
  ],
  RankingResult: [
    'id',
    'runId',
    'candidateId',
    'snapshotHash',
    'profileVersion',
    'track',
    'componentScoresJson',
    'penaltiesJson',
    'finalScore',
    'category',
    'confidence',
    'rank',
    'createdAt',
  ],
  ShortlistOptimizationResult: [
    'id',
    'runId',
    'track',
    'eligibleCandidateIdsJson',
    'finalCoverageResultId',
    'algorithmId',
    'algorithmVersion',
    'snapshotHash',
    'createdAt',
  ],
  ShortlistSelectionStep: [
    'id',
    'shortlistOptimizationResultId',
    'step',
    'selectedCandidateId',
    'marginalCoverageGain',
    'cumulativeCoverage',
    'reasonCode',
    'createdAt',
  ],
  Session: ['id', 'userId', 'tokenHash', 'expiresAt', 'createdAt'],
  StructureModel: [
    'id',
    'name',
    'source',
    'sourceReference',
    'format',
    'artifactPath',
    'sha256',
    'sequenceHash',
    'provider',
    'providerVersion',
    'status',
    'createdAt',
  ],
  User: ['id', 'email', 'displayName', 'passwordHash', 'createdAt', 'updatedAt'],
  WorkflowEvent: [
    'id',
    'runId',
    'stageId',
    'sequenceNumber',
    'eventType',
    'level',
    'message',
    'payloadJson',
    'createdAt',
  ],
  WorkflowRun: [
    'id',
    'projectId',
    'proteinInputId',
    'revision',
    'status',
    'quality',
    'configurationJson',
    'configurationHash',
    'ruleProfileVersion',
    'rankingProfileVersion',
    'requestedExecutionMode',
    'executionMode',
    'replayHash',
    'failureCode',
    'createdAt',
    'startedAt',
    'completedAt',
    'updatedAt',
  ],
  WorkflowStage: [
    'id',
    'runId',
    'stageKey',
    'attempt',
    'status',
    'dependencyKeysJson',
    'inputHash',
    'outputHash',
    'progress',
    'errorCode',
    'startedAt',
    'completedAt',
    'createdAt',
    'updatedAt',
  ],
} as const;

describe('Prisma schema conformance', () => {
  it('contains exactly the DATABASE_SCHEMA.md models and scalar fields', () => {
    const actual = Object.fromEntries(
      Prisma.dmmf.datamodel.models.map((model) => [
        model.name,
        model.fields.filter((field) => field.kind === 'scalar').map((field) => field.name),
      ]),
    );

    expect(actual).toEqual(expectedModels);
    expect(Object.keys(actual)).not.toContain('RuleProfile');
    expect(Object.keys(actual)).not.toContain('WeightProfile');
    expect(Object.keys(actual)).not.toContain('BiologicalConstraint');
  });
});
